#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro eunomia service queue current"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  cd ${PLUGIN_DIR}/config/service
  docker-compose exec $PLUGIN_EUNOMIA_SERVICE_NAME sh -c "cat $PLUGIN_EUNOMIA_TASK_QUEUE_LOCK"
}

run() {
  core "$@"
}

run "$@"
