version: '3.7'

services:
  zmicro_plugin_eunomia:
    restart: always
    image: whatwewant/pipeline-builder-eunomia:v1
    # container_name: ${PLUGIN_EUNOMIA_SERVICE_NAME}
    ports:
      - 0.0.0.0:${PLUGIN_EUNOMIA_SERVICE_PORT}:8080
    environment:
      PLUGIN_EUNOMIA_DOCKER_REGISTRY: ${PLUGIN_EUNOMIA_DOCKER_REGISTRY}
      # 3 required
      # PLUGIN_EUNOMIA_BUILD_ID: 666
      # PLUGIN_EUNOMIA_DOWNLOAD_PKG: /data/flow/ta-multiverse.tar.gz
      #
      # Question: failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests v1]: 401 Unauthorized
      # Reason: Old Docker Desktop version on Mac M1
      # Solution: https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0
      # DOCKER_BUILDKIT: 0
      #
      # Question: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
      # Solution: https://docs.docker.com/develop/develop-images/build_enhancements/
      DOCKER_BUILDKIT: 1
      # PLUGIN_EUNOMIA_TASK_QUEUE_IS_ENABLED: 'false'
    volumes:
      # # DEBUG START
      # - /usr/local/lib/zmicro:/usr/local/lib/zmicro
      # - /usr/local/lib/zmicro/plugins/eunomia/entrypoint.sh:/entrypoint.sh
      # # DEBUG END
      #
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/root/.docker/config.json
      #
      - ${PLUGIN_DATA}:/data/plugins/eunomia
      #
      - ${PLUGIN_EUNOMIA_DOCKERFILES_DIR}:${PLUGIN_EUNOMIA_DOCKERFILES_DIR}
      - ${PLUGIN_EUNOMIA_TMP_DIR}:${PLUGIN_EUNOMIA_TMP_DIR}

networks:
  default:
    external: true
    name: compose-ingress
