#!/bin/bash

# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
set -o pipefail

help() {
  echo "Usage:"
  echo "  zmicro eunomia combine"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @TODO avoid to re base64 decode
  export FLOW_CI=false

  zmicro eunomia pre
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][idp] failed to eunomia pre."
    return 1
  fi

  export EUNOMIA_GIT_CHECKOUT_DIR=$EUNOMIA_BUILD_GIT_DIR

  if [ "$EUNOMIA_SKIP_BUILD_STAGE" != "true" ]; then
    zmicro eunomia checkout
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)][idp] failed to eunomia checkout."
      return 1
    fi

    zmicro eunomia build
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)][idp] failed to eunomia build."
      return 1
    fi
  fi

  zmicro eunomia deploy
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][idp] failed to eunomia deploy."
    return 1
  fi

  if [ "$EUNOMIA_PROJECT_ENABLE_AUTO_TEST" = "true" ]; then
    zmicro eunomia test
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)][idp] failed to eunomia deploy."
      return 1
    fi
  fi

  zmicro eunomia post
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][idp] failed to eunomia post."
    return 1
  fi
}

run() {
  if [ -z "$EUNOMIA_BUILD_ID" ]; then
    log::error "[$(timestamp)][idp] EUNOMIA_BUILD_ID is required"
    exit 1
  fi

  # must mkdir or tee log file not found in docker flow
  if [ ! -d "$EUNOMIA_BUILD_DIR" ]; then
    mkdir -p $EUNOMIA_BUILD_DIR
  fi

  log::info "[$(timestamp)][idp] start to run ..."

  # start
  eunomia::hook_start

  core "$@" | tee -a $EUNOMIA_BUILD_LOG
  # end
  if [ "$?" != "0" ]; then
    eunomia::hook_failed
    log::info "[$(timestamp)][idp] failed to run."
    exit 1
  else
    eunomia::hook_succeed
    log::info "[$(timestamp)][idp] succeed to run."
    exit 0
  fi
}

run "$@"
