#!/bin/bash

set -e

help() {
  echo "Usage:"
  echo "  zmicro eunomia build"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  eunomia::build
}

run() {
  core $@
}

run $@
