#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro eunomia checkout"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)][checkout] checkouting with $EUNOMIA_GIT_REPOSITORY at $EUNOMIA_GIT_BRANCH ..."
  eunomia::checkout
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][checkout] failed to checkout git repo."
    return 1
  fi

  log::success "[$(timestamp)][checkout] succeed to checkout git repo."
}

run() {
  core "$@"
}

run "$@"
