#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro eunomia checkout"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)][checkout] checkouting with $EUNOMIA_GIT_REPOSITORY at $EUNOMIA_GIT_BRANCH ..."
  eunomia::checkout
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][checkout] failed to checkout git repo."
    exit 1
  fi

  log::success "[$(timestamp)][checkout] succeed to checkout git repo."
}

run() {
  local log=$EUNOMIA_BUILD_DIR/checkout.log
  core "$@" 2>&1 | tee -a $log
  if [ -f "$log" ]; then
    eunomia::hook_log $log
  fi
}

run "$@"
