#!/bin/bash

set -e

help() {
  echo "Usage:"
  echo "  zmicro eunomia deploy"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # @TODO avoid to re base64 decode
  export FLOW_CI=false

  eunomia::show_version_info

  # eunomia::prepare
  # if [ "$?" != "0" ]; then
  #   log::error "[deploy] failed to prepare"
  #   exit 1
  # fi

  if [ "$EUNOMIA_DEPLOYMENT_IGNORE" = "true" ]; then
    log::info "[$(timestamp)][deploy] ignore deploy because EUNOMIA_DEPLOYMENT_IGNORE is true"
    return 0
  fi

  eunomia::deploy
  if [ "$?" != "0" ]; then
    log::error "[deploy] failed to deploy"
    exit 1
  fi
}

run() {
  # start
  # eunomia::hook_deploy_start

  set -o pipefail
  core "$@" 2>&1 | tee -a $EUNOMIA_DEPLOY_LOG
  # end
  if [ "$?" != "0" ]; then
    eunomia::hook_deploy_failed
    log::info "[$(timestamp)][deploy] failed to deploy."
    exit 1
  else
    eunomia::hook_deploy_succeed
    log::info "[$(timestamp)][deploy] succeed to deploy."
    exit 0
  fi
}

run "$@"
