#!/bin/bash

# set -x
set -e

help() {
  echo "Usage:"
  echo "  zmicro eunomia export"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  eunomia::show_version_info

  eunomia::prepare
  if [ "$?" != "0" ]; then
    log::error "[build] failed to prepare"
    exit 1
  fi

  eunomia::export
  if [ "$?" != "0" ]; then
    log::error "[build] failed to export"
    exit 1
  fi
}

run() {
  core $@
}

run $@
