#!/bin/bash

# set -x
set -e

help() {
  echo "Usage:"
  echo "  zmicro eunomia export"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  eunomia::prepare

  eunomia::export
}

run() {
  core $@
}

run $@
