#!/bin/bash

set -e

help() {
  echo "Usage:"
  echo "  zmicro eunomia flow"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # build
  eunomia::build build
  # export
  eunomia::build export
}

run() {
  core $@
}

run $@
