#!/bin/bash

set -e

help() {
  echo "Usage:"
  echo "  zmicro eunomia flow"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  log::info "[$(timestamp)][flow] parering ..."
  eunomia::prepare

  if [ -n "$FORCE_BUILD" ]; then
    # build
    log::info "[$(timestamp)][flow] building ..."
    eunomia::build
  else
    log::info "[$(timestamp)][flow] checking ..."
    if [ "$(eunomia::is_built)" != "true" ]; then
      # build
      log::info "[$(timestamp)][flow] building ..."
      eunomia::build
    else
      log::info "[$(timestamp)][flow] loading cache ..."
      # @TODO create build dir for export and other steps
      mkdir -p $PLUGIN_EUNOMIA_BUILD_ID_DIR
    fi
  fi

  # export
  log::info "[flow] exporting ..."
  eunomia::export

  # done
  log::info "[flow] done"
}

run() {
  core $@
}

run $@
