#!/bin/bash

# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
set -o pipefail

help() {
  echo "Usage:"
  echo "  zmicro eunomia post"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  if [ -n "$EUNOMIA_GIT_BRANCH" ]; then
    log::info "[$(timestamp)][post] branch: $EUNOMIA_GIT_BRANCH (commit: $EUNOMIA_GIT_COMMIT)"
  else
    log::info "[$(timestamp)][post] not a git repo pipeline."
  fi
}

run() {
  local log=$EUNOMIA_BUILD_DIR/post.log
  core "$@" 2>&1 | tee -a $log
  if [ "$?" != "0" ]; then
    eunomia::hook_log $log
    exit 1
  else
    eunomia::hook_log $log
    exit 0
  fi
}

run "$@"
