#!/bin/bash

# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
set -o pipefail

help() {
  echo "Usage:"
  echo "  zmicro eunomia pre"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  eunomia::show_version_info

  log::info "[$(timestamp)][pre] build id: $EUNOMIA_BUILD_ID"
  log::info "[$(timestamp)][pre] executor: $EUNOMIA_BUILD_AUTHOR($EUNOMIA_BUILD_AUTHOR_EMAIL)"
  log::info "[$(timestamp)][pre] git info:"
  log::info "[$(timestamp)][pre]  url: $EUNOMIA_GIT_REPOSITORY"
  log::info "[$(timestamp)][pre]  branch: $EUNOMIA_GIT_BRANCH"
  log::info "[$(timestamp)][pre]  commit hash: $EUNOMIA_GIT_COMMIT"
  log::info "[$(timestamp)][pre]  commit message: $EUNOMIA_GIT_COMMIT_MESSAGE"
  log::info "[$(timestamp)][pre]  commit author: $EUNOMIA_GIT_COMMIT_AUTHOR"
  log::info "[$(timestamp)][pre]  commit timestamp: $EUNOMIA_GIT_COMMIT_TIMESTAMP"
}

run() {
  local log=$EUNOMIA_BUILD_DIR/pre.log
  core "$@" 2>&1 | tee -a $log
  if [ "$?" != "0" ]; then
    eunomia::hook_log $log
    exit 1
  else
    eunomia::hook_log $log
    exit 0
  fi
}

run "$@"
