#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro eunomia docker service config"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  cd ${PLUGIN_DIR}/config/service
  docker-compose config
}

run() {
  core $@
}

run $@
