#!/bin/bash

# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
set -o pipefail

help() {
  echo "Usage:"
  echo "  zmicro eunomia docker flow"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  if [ -z "$PLUGIN_EUNOMIA_BUILD_ID" ]; then
    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_BUILD_ID is required"
    exit 1
  fi
  
  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_NAME" ]; then
    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_GIT_REPO_NAME is required"
    exit 1
  fi

  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_PKG" ]; then
    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_GIT_REPO_PKG is required"
    exit 1
  fi

  echo $PLUGIN_EUNOMIA_GIT_REPO_PKG | grep $PLUGIN_EUNOMIA_GIT_REPO_PKG_TMP_DIR >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_GIT_REPO_PKG(${PLUGIN_EUNOMIA_GIT_REPO_PKG}) must be starts with ${PLUGIN_EUNOMIA_GIT_REPO_PKG_TMP_DIR}"
    exit 1
  fi

  # start
  eunomia::hook_start

  cd ${PLUGIN_DIR}/config/service
  docker-compose exec \
    -T \
    -e PLUGIN_EUNOMIA_BUILD_ID=${PLUGIN_EUNOMIA_BUILD_ID} \
    -e PLUGIN_EUNOMIA_GIT_REPO_NAME=${PLUGIN_EUNOMIA_GIT_REPO_NAME} \
    -e PLUGIN_EUNOMIA_GIT_REPO_PKG=${PLUGIN_EUNOMIA_GIT_REPO_PKG} \
    -e PLUGIN_EUNOMIA_EXECUTOR_EMAIL=${PLUGIN_EUNOMIA_EXECUTOR_EMAIL} \
    -e PLUGIN_EUNOMIA_EXECUTOR_NAME=${PLUGIN_EUNOMIA_EXECUTOR_NAME} \
    -e PLUGIN_EUNOMIA_EXECUTOR_ID=${PLUGIN_EUNOMIA_EXECUTOR_ID} \
    zmicro_plugin_eunomia \
    zmicro eunomia flow

  # end
  if [ "$?" != "0" ]; then
    eunomia::hook_failed
    exit 1
  else
    eunomia::hook_succeed
    exit 0
  fi
}

run() {
  core $@ | tee -a $PLUGIN_EUNOMIA_BUILD_LOG
}

run $@
