#!/bin/bash

# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
set -o pipefail

help() {
  echo "Usage:"
  echo "  zmicro eunomia docker flow"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  eunomia::show_version_info

  # @TODO avoid to re base64 decode
  export FLOW_CI=false

  if [ -n "$EUNOMIA_GIT_REPOSITORY" ] && [ -n "$EUNOMIA_GIT_BRANCH" ] && [ -n "$EUNOMIA_GIT_COMMIT" ]; then
    export EUNOMIA_GIT_CHECKOUT_DIR=$(os::tmp_dir)
    export PLUGIN_EUNOMIA_DOWNLOAD_PKG="${PLUGIN_EUNOMIA_TMP_DIR}/$(os::random_string 8).tar.gz"
    
    zmicro eunomia checkout
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)][docker][flow] failed to eunomia checkout."
      return 1
    fi

    log::info "[$(timestamp)][checkout] creating DOWNLOAD_PKG at $PLUGIN_EUNOMIA_DOWNLOAD_PKG ..."
    cd $EUNOMIA_GIT_CHECKOUT_DIR
    tar -zcvf $PLUGIN_EUNOMIA_DOWNLOAD_PKG ./ >>/dev/null
    if [ "$?" != "0" ]; then
      log::error "[$(timestamp)][checkout] failed to create DOWNLOAD_PKG."
      return 1
    fi
    cd -
  fi

  log::info "[$(timestamp)] EUNOMIA_BUILD_ID_DIR: $EUNOMIA_BUILD_ID_DIR"
  log::info "[$(timestamp)] PLUGIN_EUNOMIA_DOWNLOAD_PKG: $PLUGIN_EUNOMIA_DOWNLOAD_PKG"

  zmicro eunomia build
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][docker][flow] failed to eunomia build."
    return 1
  fi
}

run() {
  core "$@"
}

run "$@"
