#!/bin/bash

# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
set -o pipefail

help() {
  echo "Usage:"
  echo "  zmicro eunomia docker run"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  # run disable export dist
  export PLUGIN_EUNOMIA_EXPORT_DISABLE=true
  zmicro eunomia docker flow
}

run() {
  core
}

run $@
