#!/bin/bash

eunomia::build() {
  # eunomia::prepare
  eunomia::prepare

  # Dockerfile
  cp ${PLUGIN_DIR}/config/docker/Dockerfile $PLUGIN_EUNOMIA_GIT_REPO_DIR

  zmicro pipeline bp
}

export -f eunomia::build
