#!/bin/bash

eunomia::check_build() {
  if [ -z "$PLUGIN_EUNOMIA_RUNNER_IMAGE" ]; then
    log::error "[check_build] PLUGIN_EUNOMIA_RUNNER_IMAGE is required"
    exit 1
  fi

  docker pull $PLUGIN_EUNOMIA_RUNNER_IMAGE >> /dev/null 2>&1
  if [ "$?" != "0" ]; then
    echo "false"
  else
    echo "true"
  fi
}

export -f eunomia::check_build
