#!/bin/bash

eunomia::hook_log() {
  if [ -z "$EUNOMIA_BUILD_DIR" ]; then
    log::error "[eunomia::hook_log] EUNOMIA_BUILD_DIR is required"
    return 1
  fi

  if [ ! -d "$EUNOMIA_BUILD_DIR" ]; then
    log::error "[eunomia::hook_log] EUNOMIA_BUILD_DIR($EUNOMIA_BUILD_DIR) not found"
    return 1
  fi

  if [ -n "$EUNOMIA_LOG_HOOK" ]; then
    if [ ! -f "$EUNOMIA_BUILD_LOG" ]; then
      log::info "[$(timestamp)][eunomia::hook_log] build log($EUNOMIA_BUILD_LOG) is not found"
      return
    fi

    log::info "[$(timestamp)][eunomia::hook_log] call $EUNOMIA_LOG_HOOK with log(file: $EUNOMIA_BUILD_LOG)..."

    curl \
      -s \
      -X POST \
      --data-binary "@$EUNOMIA_BUILD_LOG" \
      $EUNOMIA_LOG_HOOK >>/dev/null
    # -d "$(cat $EUNOMIA_BUILD_LOG)"
  fi
}

eunomia::hook_start() {
  if [ -n "$EUNOMIA_START_HOOK" ]; then
    log::info "[$(timestamp)][eunomia::hook_start] call $EUNOMIA_START_HOOK ..."

    local FLOW_PIPELINE_ID=$(echo $EUNOMIA_BUILD_ID | awk -F '_' '{print $1}')
    local FLOW_BUILD_ID=$(echo $EUNOMIA_BUILD_ID | awk -F '_' '{print $2}')

    curl \
      -s \
      -X POST $EUNOMIA_START_HOOK \
      -H "Content-Type: application/json" \
      --data-binary @- <<EOF
{
    "flow_pipeline_id": "$FLOW_PIPELINE_ID",
    "flow_build_id": "$FLOW_BUILD_ID",
    "git_repo_url": "$EUNOMIA_GIT_REPO_URL",
    "git_repo_name": "$EUNOMIA_GIT_REPO_NAME",
    "git_branch": "$EUNOMIA_GIT_BRANCH",
    "git_commit": "$EUNOMIA_GIT_COMMIT",
    "git_commit_message": "$EUNOMIA_GIT_COMMIT_MESSAGE",
    "git_commit_author": "$EUNOMIA_GIT_COMMIT_AUTHOR",
    "git_commit_timestamp": "$EUNOMIA_GIT_COMMIT_TIMESTAMP",
    "build_id": "$EUNOMIA_BUILD_ID",
    "build_timestamp": "$EUNOMIA_BUILD_TIMESTAMP",
    "build_author": "$EUNOMIA_BUILD_AUTHOR",
    "build_author_email": "$EUNOMIA_BUILD_AUTHOR_EMAIL"
}
EOF
  fi
}

eunomia::hook_succeed() {
  if [ -n "$EUNOMIA_SUCCEED_HOOK" ]; then
    log::info "[$(timestamp)][eunomia::hook_succeed] call $EUNOMIA_SUCCEED_HOOK ..."
    curl -s -X POST $EUNOMIA_SUCCEED_HOOK >>/dev/null

    eunomia::hook_log
  fi
}

eunomia::hook_failed() {
  if [ -n "$EUNOMIA_FAILED_HOOK" ]; then
    log::info "[$(timestamp)][eunomia::hook_failed] call $EUNOMIA_FAILED_HOOK ..."
    curl -s -X POST $EUNOMIA_FAILED_HOOK >>/dev/null

    eunomia::hook_log
  fi
}

export -f eunomia::hook_log
export -f eunomia::hook_start
export -f eunomia::hook_succeed
export -f eunomia::hook_failed
