#!/bin/bash

# gvm::current gets the current version of Go
eunomia::prepare() {
  if [ -z "$PLUGIN_EUNOMIA_BUILD_ID" ]; then
    log::error "[prepare] PLUGIN_EUNOMIA_BUILD_ID is required"
    exit 1
  fi

  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_NAME" ]; then
    log::error "[prepare] PLUGIN_EUNOMIA_GIT_REPO_NAME is required"
    exit 1
  fi

  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_PKG" ]; then
    log::error "[prepare] PLUGIN_EUNOMIA_GIT_REPO_PKG is required"
    exit 1
  fi

  if  [ ! -f "$PLUGIN_EUNOMIA_GIT_REPO_PKG" ]; then
    log::error "[prepare] PLUGIN_EUNOMIA_GIT_REPO_PKG($PLUGIN_EUNOMIA_GIT_REPO_PKG) is not a file"
    exit 1
  fi

  mkdir -p $PLUGIN_EUNOMIA_GIT_REPO_DIR
  # mkdir -p $PLUGIN_EUNOMIA_BUILD_ID_DIR
}

export -f eunomia::prepare
