#!/bin/bash

eunomia::run() {
  if [ -z "$PLUGIN_EUNOMIA_BUILD_GIT_DIR" ]; then
    log::error "[eunomia::run] PLUGIN_EUNOMIA_BUILD_GIT_DIR is required"
    return 1
  fi

  if [ ! -d "$PLUGIN_EUNOMIA_BUILD_GIT_DIR" ]; then
    log::error "[eunomia::run] PLUGIN_EUNOMIA_BUILD_GIT_DIR($PLUGIN_EUNOMIA_BUILD_GIT_DIR) not found, you must run prepare first"
    return 1
  fi

  log::info "[eunomia::run] start ..."

  # Dockerfile
  # RSYNC DOKCERFILE_DIR/*
  # @TODO with "DIR/" suffix copy file
  if [ -n "$PLUGIN_EUNOMIA_DOCKERFILE_MODULE" ]; then
    # 子模块
    rsync -av ${PLUGIN_EUNOMIA_DOCKERFILE_DIR_FOR_GIT_REPO}/$PLUGIN_EUNOMIA_DOCKERFILE_MODULE/ $PLUGIN_EUNOMIA_BUILD_GIT_DIR
  else
    # 主模块
    # rsync -av --exclude="$PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO" ${PLUGIN_EUNOMIA_DOCKERFILE_DIR_FOR_GIT_REPO}/ $PLUGIN_EUNOMIA_BUILD_GIT_DIR
    rsync -av ${PLUGIN_EUNOMIA_DOCKERFILE_DIR_FOR_GIT_REPO}/ $PLUGIN_EUNOMIA_BUILD_GIT_DIR
  fi

  # ADD build files for dockerfile
  echo "EUNOMIA_GIT_REPO_URL: $PLUGIN_EUNOMIA_GIT_REPO_URL" >$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_GIT_REPO_NAME: $PLUGIN_EUNOMIA_GIT_REPO_NAME" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_GIT_BRANCH: $PLUGIN_EUNOMIA_GIT_BRANCH" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_GIT_COMMIT: $PLUGIN_EUNOMIA_GIT_COMMIT" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_GIT_COMMIT_MESSAGE: $PLUGIN_EUNOMIA_GIT_COMMIT_MESSAGE" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_GIT_COMMIT_AUTHOR: $PLUGIN_EUNOMIA_GIT_COMMIT_AUTHOR" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_GIT_COMMIT_TIMESTAMP: $PLUGIN_EUNOMIA_GIT_COMMIT_TIMESTAMP" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  #
  echo "EUNOMIA_BUILD_ID: $EUNOMIA_BUILD_ID" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_BUILD_AUTHOR: ${EUNOMIA_BUILD_AUTHOR}" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_BUILD_AUTHOR_EMAIL: ${EUNOMIA_BUILD_AUTHOR_EMAIL}" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_BUILD_TIMESTAMP: $EUNOMIA_BUILD_TIMESTAMP" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  #
  echo "EUNOMIA_PROJECT_ID: $EUNOMIA_PROJECT_ID" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_TASK_ID: $EUNOMIA_TASK_ID" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_DEPLOYMENT_ID: $EUNOMIA_DEPLOYMENT_ID" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js
  echo "EUNOMIA_JOB_ID: $EUNOMIA_JOB_ID" >>$PLUGIN_EUNOMIA_BUILD_GIT_DIR/build.eunomia.js

  # @DEPRECIATED @TO_REMOVE
  echo "$EUNOMIA_BUILD_ID" >$PLUGIN_EUNOMIA_BUILD_GIT_DIR/buildid.eunomia.js
  echo "$EUNOMIA_BUILD_TIMESTAMP" >$PLUGIN_EUNOMIA_BUILD_GIT_DIR/buildtime.eunomia.js

  log::info "[eunomia::run] build ..."
  zmicro pipeline once run
  if [ "$?" != "0" ]; then
    log::error "[eunomia::run] failed to run"
    return 1
  fi

  # clean
  rm -rf $PLUGIN_EUNOMIA_BUILD_GIT_DIR

  log::info "[eunomia::run] done"
}

export -f eunomia::run
