#!/bin/bash

eunomia::sync_dockerfiles() {
  if [ -z "$PLUGIN_EUNOMIA_DOCKERFILES_DIR" ]; then
    log::error "[$(timestamp)][eunomia::sync_dockerfiles] PLUGIN_EUNOMIA_DOCKERFILES_DIR is required"
    return 1
  fi

  if [ ! -d "$PLUGIN_EUNOMIA_DOCKERFILES_DIR" ]; then
    log::error "[$(timestamp)][eunomia::sync_dockerfiles] export directory($PLUGIN_EUNOMIA_DOCKERFILES_DIR) already exists"
    return 1
  fi

  log::info "[$(timestamp)][eunomia::sync_dockerfiles] start ..."

  cd $PLUGIN_EUNOMIA_DOCKERFILES_DIR
  git pull origin master >>/dev/null
  if [ "$?" != "0" ]; then
    log::error "[$(timestamp)][eunomia::sync_dockerfiles] failed to sync dockerfiles"
    return 1
  fi

  local timestamp=$(os::timestamp)
  local git_hash=$(git::commit_hash)
  local git_commit_message=$(git::commit_message)
  local git_commit_author=$(git::commit_author)
  local git_repo_url=$(git::repo_url)
  notify::feishu $PLUGIN_EUNOMIA_NOTIFICATION_FEISHU_URL "[$(timestamp)] Dockerfiles 同步" "状态: 成功\n变更: ${git_commit_message}\n修改人: ${git_commit_author}\nHash: ${git_hash}\nURL: ${git_repo_url}\n当前时间: $timestamp"

  log::info "[$(timestamp)][eunomia::sync_dockerfiles] done"
}

export -f eunomia::sync_dockerfiles
