#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro eunomia schedule clean"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  eunomia::schedule_clean
}

run() {
  core "$@"
}

run "$@"
