services:
  <PLUGIN_EUNOMIA_DEPLOYMENT_NAME>:
    container_name: ${PLUGIN_EUNOMIA_DEPLOYMENT_NAME}
    restart: always
    image: ${PLUGIN_EUNOMIA_DOCKER_REGISTRY}/${PLUGIN_EUNOMIA_DEPLOYMENT_IMAGE_NAME}:build_${EUNOMIA_BUILD_ID}
    environment:
      PORT: 8080
      TZ: Asia/Shanghai
    env_file:
      - ${EUNOMIA_DEPLOYMENT_ENV_CONFIG}
      - ${EUNOMIA_BUILD_ENV_SHELL}
    mem_limit: "${EUNOMIA_DEPLOYMENT_MEM_LIMIT}m"
    cpus: ${EUNOMIA_DEPLOYMENT_CPU_LIMIT}
    volumes:
      - ${PLUGIN_EUNOMIA_DEPLOYMENT_DATA_DIR}:/data
    networks:
      default:
        aliases:
          - ${PLUGIN_EUNOMIA_DEPLOYMENT_EXTRA_HOSTNAME}

networks:
  default:
    external: true
    name: compose-ingress
